input.onButtonPressed(Button.A, function () {
    led.plot(0, 0)
    basic.pause(500)
    led.unplot(0, 0)
    basic.pause(500)
    led.plot(0, 1)
    basic.pause(500)
    led.unplot(0, 1)
    basic.pause(500)
    led.plot(0, 2)
    basic.pause(500)
    led.unplot(0, 2)
    basic.pause(500)
    led.plot(0, 3)
    basic.pause(500)
    led.unplot(0, 3)
    basic.pause(500)
    led.plot(0, 4)
    basic.pause(500)
    led.unplot(0, 4)
})
basic.forever(function () {
	
})
